import{a as L,S as b,i as u}from"./assets/vendor-b42c18af.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const v="42731864-a3c3d068e2b72bbf390461e5a";async function h(t,e){const s=new URLSearchParams({key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:15});return(await L.get(`https://pixabay.com/api/?${s}`)).data}const f=document.querySelector(".gallery-ul");function m(t){let e="";for(let s in t.hits)e+=`
        <li class="gallery-item">
        <a href="${t.hits[s].largeImageURL}"><img class="photo-img" src="${t.hits[s].largeImageURL}"></a>
        <ul class="gallery-info">
        <li class="info-item"><h3 class="photo-header">Likes</h3>
        <p class="photo-value">${t.hits[s].likes}</p></li>
        <li class="info-item"><h3 class="photo-header">Views</h3>
       <p class="photo-value">${t.hits[s].views}</p></li>
        <li class="info-item"><h3 class="photo-header">Comments</h3>
        <p class="photo-value">${t.hits[s].comments}</p></li>
        <li class="info-item"><h3 class="photo-header">Downloads</h3>
        <p class="photo-value">${t.hits[s].downloads}</p></li>
        </ul>
        <li>`;f.insertAdjacentHTML("beforeend",e)}function S(){f.innerHTML=""}const c=document.querySelector(".search-input"),q=document.querySelector(".search-btn"),d=document.querySelector(".more-btn"),g=document.querySelector(".loader");let y=new b(".gallery a",{captionsData:"alt",captionDelay:250}),l,p=1;function w(){g.style.display="flex"}function i(){g.style.display="none"}q.addEventListener("click",t=>{t.preventDefault(),l=c.value,c.value===""?u.show({title:"Warning",message:"search input is empty!",position:"topLeft",backgroundColor:"yellow"}):(w(),h(l,p=1).then(e=>{i(),S(),e.hits.length>0?(m(e),y.refresh(),d.style.display="block"):u.show({title:"Error",message:"Image not found",position:"topLeft",backgroundColor:"red"})}).catch(e=>{i(),console.log(e)}),c.value="")});d.addEventListener("click",async t=>{t.preventDefault();const e=await h(l,p);w();try{h(l,p+=1),i(),e.hits.length>0?(m(e),y.refresh(),P()):(u.show({title:"Error",message:"No more images found",position:"topLeft",backgroundColor:"red"}),d.style.display="none")}catch(s){i(),console.log(s)}});function P(){const e=document.querySelector(".photo-img").getBoundingClientRect(),s=e.width*e.height;window.scroll({top:window.scrollY+s,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
