import{a as L,S as b,i as n}from"./assets/vendor-b42c18af.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const v="42731864-a3c3d068e2b72bbf390461e5a";async function d(t,e){const s=new URLSearchParams({key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:15});return(await L.get(`https://pixabay.com/api/?${s}`)).data}const p=document.querySelector(".gallery-ul");function f(t){let e="";for(let s in t.hits)e+=`
        <li class="gallery-item">
        <a href="${t.hits[s].largeImageURL}"><img class="photo-img" src="${t.hits[s].largeImageURL}"></a>
        <ul class="gallery-info">
        <li class="info-item"><h3 class="photo-header">Likes</h3>
        <p class="photo-value">${t.hits[s].likes}</p></li>
        <li class="info-item"><h3 class="photo-header">Views</h3>
       <p class="photo-value">${t.hits[s].views}</p></li>
        <li class="info-item"><h3 class="photo-header">Comments</h3>
        <p class="photo-value">${t.hits[s].comments}</p></li>
        <li class="info-item"><h3 class="photo-header">Downloads</h3>
        <p class="photo-value">${t.hits[s].downloads}</p></li>
        </ul>
        <li>`;p.insertAdjacentHTML("beforeend",e)}function S(){p.innerHTML=""}const i=document.querySelector(".search-input"),q=document.querySelector(".search-btn"),c=document.querySelector(".more-btn"),m=document.querySelector(".loader");let g=new b(".gallery a",{captionsData:"alt",captionDelay:250}),u,h=1;function y(){m.style.display="flex"}function w(){m.style.display="none"}q.addEventListener("click",async t=>{if(t.preventDefault(),u=i.value,i.value==="")n.show({title:"Warning",message:"search input is empty!",position:"topLeft",backgroundColor:"yellow"});else{y();try{const e=await d(u,h=1);w(),S(),e.hits.length>0?(f(e),g.refresh(),c.style.display="block"):n.show({title:"Error",message:"Image not found",position:"topLeft",backgroundColor:"red"})}catch{console.log(error)}i.value=""}});c.addEventListener("click",async t=>{t.preventDefault(),y(),h+=1;try{const e=await d(u,h);w(),e.hits.length>0?(f(e),g.refresh(),P()):(n.show({title:"Error",message:"No more images found",position:"topLeft",backgroundColor:"red"}),c.style.display="none")}catch(e){console.log(e)}});function P(){const e=document.querySelector(".photo-img").getBoundingClientRect(),s=e.width*e.height;window.scroll({top:window.scrollY+s,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
